package App;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tranluan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        changeColorMenu(backgroundTrainMenuPanel, backgroundTestMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(trainPanel, testPanel, classificationPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup6 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        backroundPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        wineImg = new javax.swing.JLabel();
        backgroundClassificationMenuPanel = new javax.swing.JPanel();
        classificationMenuLabel = new javax.swing.JLabel();
        backgroundTestMenuPanel = new javax.swing.JPanel();
        testMenuLabel = new javax.swing.JLabel();
        backgroundTrainMenuPanel = new javax.swing.JPanel();
        trainMenuLabel = new javax.swing.JLabel();
        trainPanel = new javax.swing.JPanel();
        trainHeadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        trainPathLine = new javax.swing.JSeparator();
        pathTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        chooseTrainFileBtn = new javax.swing.JButton();
        trainModelBtn = new javax.swing.JButton();
        saveModelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTrainModelTextArea = new javax.swing.JTextArea();
        testPanel = new javax.swing.JPanel();
        testHeadingLabel = new javax.swing.JLabel();
        pathTestLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pathTestTextField = new javax.swing.JTextField();
        pathTestLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pathTestTextField1 = new javax.swing.JTextField();
        chooseTestFileBtn = new javax.swing.JButton();
        testModelBtn = new javax.swing.JButton();
        chooseModelBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTestModelTextArea = new javax.swing.JTextArea();
        classificationPanel = new javax.swing.JPanel();
        ClassificationHeadingLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textField4 = new javax.swing.JTextField();
        textField10 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textField2 = new javax.swing.JTextField();
        textField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textField5 = new javax.swing.JTextField();
        textField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        predictTable = new javax.swing.JTable();
        predictBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        predictFileBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Red Wine Quality Measure");
        setBackground(new java.awt.Color(255, 249, 219));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        backroundPanel.setBackground(new java.awt.Color(255, 245, 245));
        backroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(250, 82, 82));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wineImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/wine-sm.png"))); // NOI18N
        wineImg.setText("jLabel5");
        sidePanel.add(wineImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 340));

        backgroundClassificationMenuPanel.setBackground(new java.awt.Color(250, 82, 82));
        backgroundClassificationMenuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundClassificationMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundClassificationMenuPanelMouseClicked(evt);
            }
        });

        classificationMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        classificationMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        classificationMenuLabel.setText("Wine Classification");
        classificationMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classificationMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classificationMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundClassificationMenuPanelLayout = new javax.swing.GroupLayout(backgroundClassificationMenuPanel);
        backgroundClassificationMenuPanel.setLayout(backgroundClassificationMenuPanelLayout);
        backgroundClassificationMenuPanelLayout.setHorizontalGroup(
            backgroundClassificationMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundClassificationMenuPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(classificationMenuLabel)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        backgroundClassificationMenuPanelLayout.setVerticalGroup(
            backgroundClassificationMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundClassificationMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classificationMenuLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(backgroundClassificationMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 250, 40));

        backgroundTestMenuPanel.setBackground(new java.awt.Color(250, 82, 82));
        backgroundTestMenuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundTestMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundTestMenuPanelMouseClicked(evt);
            }
        });

        testMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        testMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        testMenuLabel.setText("Test model");
        testMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundTestMenuPanelLayout = new javax.swing.GroupLayout(backgroundTestMenuPanel);
        backgroundTestMenuPanel.setLayout(backgroundTestMenuPanelLayout);
        backgroundTestMenuPanelLayout.setHorizontalGroup(
            backgroundTestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTestMenuPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(testMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        backgroundTestMenuPanelLayout.setVerticalGroup(
            backgroundTestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTestMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testMenuLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(backgroundTestMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        backgroundTrainMenuPanel.setBackground(new java.awt.Color(250, 82, 82));
        backgroundTrainMenuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundTrainMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundTrainMenuPanelMouseClicked(evt);
            }
        });

        trainMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trainMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        trainMenuLabel.setText("Train model");
        trainMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trainMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundTrainMenuPanelLayout = new javax.swing.GroupLayout(backgroundTrainMenuPanel);
        backgroundTrainMenuPanel.setLayout(backgroundTrainMenuPanelLayout);
        backgroundTrainMenuPanelLayout.setHorizontalGroup(
            backgroundTrainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTrainMenuPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(trainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        backgroundTrainMenuPanelLayout.setVerticalGroup(
            backgroundTrainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTrainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainMenuLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(backgroundTrainMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        backroundPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 242, 540));

        trainPanel.setBackground(new java.awt.Color(255, 245, 245));
        trainPanel.setForeground(new java.awt.Color(255, 82, 82));

        trainHeadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        trainHeadingLabel.setForeground(new java.awt.Color(250, 82, 82));
        trainHeadingLabel.setText("Train wine model");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 82, 82));
        jLabel1.setText("Path: ");

        trainPathLine.setBackground(new java.awt.Color(255, 82, 82));
        trainPathLine.setForeground(new java.awt.Color(255, 82, 82));

        pathTextField.setBackground(new java.awt.Color(255, 245, 245));
        pathTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jComboBox1.setForeground(new java.awt.Color(255, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decision tree", "KNN", "Naive Bayes", "Neural Network", "Support Vector Machine(SVM)" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 82, 82));
        jLabel2.setText("Algorithm:");

        chooseTrainFileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chooseTrainFileBtn.setForeground(new java.awt.Color(255, 82, 82));
        chooseTrainFileBtn.setText("Choose train file");
        chooseTrainFileBtn.setActionCommand("Choose file train");
        chooseTrainFileBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        chooseTrainFileBtn.setBorderPainted(false);
        chooseTrainFileBtn.setFocusPainted(false);
        chooseTrainFileBtn.setFocusable(false);
        chooseTrainFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTrainFileBtnActionPerformed(evt);
            }
        });

        trainModelBtn.setBackground(new java.awt.Color(255, 82, 82));
        trainModelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trainModelBtn.setForeground(new java.awt.Color(255, 255, 255));
        trainModelBtn.setText("Train Model");
        trainModelBtn.setActionCommand("Choose file train");
        trainModelBtn.setFocusPainted(false);
        trainModelBtn.setFocusable(false);
        trainModelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainModelBtnActionPerformed(evt);
            }
        });

        saveModelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveModelBtn.setForeground(new java.awt.Color(255, 82, 82));
        saveModelBtn.setText("Save Model");
        saveModelBtn.setActionCommand("Choose file train");
        saveModelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        saveModelBtn.setBorderPainted(false);
        saveModelBtn.setFocusPainted(false);
        saveModelBtn.setFocusable(false);
        saveModelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveModelBtnActionPerformed(evt);
            }
        });

        infoTrainModelTextArea.setEditable(false);
        infoTrainModelTextArea.setColumns(20);
        infoTrainModelTextArea.setRows(5);
        infoTrainModelTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        jScrollPane1.setViewportView(infoTrainModelTextArea);

        javax.swing.GroupLayout trainPanelLayout = new javax.swing.GroupLayout(trainPanel);
        trainPanel.setLayout(trainPanelLayout);
        trainPanelLayout.setHorizontalGroup(
            trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trainPanelLayout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(trainPanelLayout.createSequentialGroup()
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trainPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(trainHeadingLabel))
                    .addGroup(trainPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 388, Short.MAX_VALUE)
                            .addComponent(pathTextField)
                            .addComponent(trainPathLine)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chooseTrainFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(saveModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trainModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trainPanelLayout.setVerticalGroup(
            trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(trainHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(trainPathLine, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseTrainFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        backroundPanel.add(trainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 530, 540));

        testPanel.setBackground(new java.awt.Color(255, 245, 245));
        testPanel.setForeground(new java.awt.Color(255, 82, 82));

        testHeadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        testHeadingLabel.setForeground(new java.awt.Color(250, 82, 82));
        testHeadingLabel.setText("Test wine model");

        pathTestLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pathTestLabel.setForeground(new java.awt.Color(255, 82, 82));
        pathTestLabel.setText("Path: ");

        jSeparator2.setBackground(new java.awt.Color(255, 82, 82));
        jSeparator2.setForeground(new java.awt.Color(255, 82, 82));

        pathTestTextField.setBackground(new java.awt.Color(255, 245, 245));
        pathTestTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        pathTestLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pathTestLabel1.setForeground(new java.awt.Color(255, 82, 82));
        pathTestLabel1.setText("Model:");

        jSeparator3.setBackground(new java.awt.Color(255, 82, 82));
        jSeparator3.setForeground(new java.awt.Color(255, 82, 82));

        pathTestTextField1.setBackground(new java.awt.Color(255, 245, 245));
        pathTestTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        chooseTestFileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chooseTestFileBtn.setForeground(new java.awt.Color(255, 82, 82));
        chooseTestFileBtn.setActionCommand("Choose file train");
        chooseTestFileBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        chooseTestFileBtn.setBorderPainted(false);
        chooseTestFileBtn.setFocusPainted(false);
        chooseTestFileBtn.setFocusable(false);
        chooseTestFileBtn.setLabel("Choose test file");
        chooseTestFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTestFileBtnActionPerformed(evt);
            }
        });

        testModelBtn.setBackground(new java.awt.Color(255, 82, 82));
        testModelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        testModelBtn.setForeground(new java.awt.Color(255, 255, 255));
        testModelBtn.setText("Test Model");
        testModelBtn.setActionCommand("Choose file train");
        testModelBtn.setFocusPainted(false);
        testModelBtn.setFocusable(false);
        testModelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testModelBtnActionPerformed(evt);
            }
        });

        chooseModelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chooseModelBtn.setForeground(new java.awt.Color(255, 82, 82));
        chooseModelBtn.setText("Choose Model");
        chooseModelBtn.setActionCommand("Choose file train");
        chooseModelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        chooseModelBtn.setBorderPainted(false);
        chooseModelBtn.setFocusPainted(false);
        chooseModelBtn.setFocusable(false);
        chooseModelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseModelBtnActionPerformed(evt);
            }
        });

        infoTestModelTextArea.setEditable(false);
        infoTestModelTextArea.setColumns(20);
        infoTestModelTextArea.setRows(5);
        infoTestModelTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        jScrollPane2.setViewportView(infoTestModelTextArea);

        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pathTestLabel1)
                    .addComponent(pathTestLabel))
                .addGap(18, 18, 18)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(pathTestTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(pathTestTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testPanelLayout.createSequentialGroup()
                        .addComponent(testHeadingLabel)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testPanelLayout.createSequentialGroup()
                        .addComponent(chooseTestFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(chooseModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(testHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addComponent(pathTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pathTestTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addComponent(pathTestLabel)
                        .addGap(36, 36, 36)
                        .addComponent(pathTestLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseTestFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        backroundPanel.add(testPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 530, 540));

        classificationPanel.setBackground(new java.awt.Color(255, 245, 245));
        classificationPanel.setForeground(new java.awt.Color(255, 82, 82));

        ClassificationHeadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ClassificationHeadingLabel.setForeground(new java.awt.Color(250, 82, 82));
        ClassificationHeadingLabel.setText("Wine Classification");

        jLabel3.setForeground(new java.awt.Color(255, 82, 82));
        jLabel3.setText("Fixed acidity:");

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 82, 82));
        jLabel4.setText("Residual sugar: ");

        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        });

        textField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField10ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 82, 82));
        jLabel5.setText("Sulphates:");

        jLabel6.setForeground(new java.awt.Color(255, 82, 82));
        jLabel6.setText("Alcohol:");

        textField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField11ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 82, 82));
        jLabel7.setText("Volatile acidity: ");

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });

        textField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField8ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 82, 82));
        jLabel8.setText("Density:");

        textField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField9ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 82, 82));
        jLabel9.setText("pH:");

        jLabel10.setForeground(new java.awt.Color(255, 82, 82));
        jLabel10.setText("Citric acid:");

        textField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField3ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 82, 82));
        jLabel11.setText("Chlorides:");

        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });

        textField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField6ActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 82, 82));
        jLabel12.setText("Free sulfur dioxide:");

        textField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField7ActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 82, 82));
        jLabel13.setText("Total sulfur dioxide:");

        predictTable.setForeground(new java.awt.Color(255, 82, 82));
        predictTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        predictTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        predictTable.setSelectionForeground(new java.awt.Color(255, 82, 82));
        jScrollPane3.setViewportView(predictTable);

        predictBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        predictBtn.setForeground(new java.awt.Color(255, 82, 82));
        predictBtn.setText("Predict");
        predictBtn.setActionCommand("Choose file train");
        predictBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        predictBtn.setBorderPainted(false);
        predictBtn.setFocusPainted(false);
        predictBtn.setFocusable(false);

        exportBtn.setBackground(new java.awt.Color(255, 82, 82));
        exportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exportBtn.setForeground(new java.awt.Color(255, 255, 255));
        exportBtn.setText("Export");
        exportBtn.setActionCommand("Choose file train");
        exportBtn.setFocusPainted(false);
        exportBtn.setFocusable(false);
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        predictFileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        predictFileBtn.setForeground(new java.awt.Color(255, 82, 82));
        predictFileBtn.setText("Predict File");
        predictFileBtn.setActionCommand("Choose file train");
        predictFileBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 82, 82), 1, true));
        predictFileBtn.setBorderPainted(false);
        predictFileBtn.setFocusPainted(false);
        predictFileBtn.setFocusable(false);
        predictFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout classificationPanelLayout = new javax.swing.GroupLayout(classificationPanel);
        classificationPanel.setLayout(classificationPanelLayout);
        classificationPanelLayout.setHorizontalGroup(
            classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classificationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classificationPanelLayout.createSequentialGroup()
                        .addComponent(ClassificationHeadingLabel)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classificationPanelLayout.createSequentialGroup()
                        .addComponent(predictBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(predictFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(classificationPanelLayout.createSequentialGroup()
                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classificationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12))
                    .addGroup(classificationPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)))
                .addContainerGap())
        );
        classificationPanelLayout.setVerticalGroup(
            classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classificationPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ClassificationHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classificationPanelLayout.createSequentialGroup()
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(classificationPanelLayout.createSequentialGroup()
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(textField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(textField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(classificationPanelLayout.createSequentialGroup()
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(textField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(textField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(predictBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predictFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        backroundPanel.add(classificationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 530, 540));

        closeBtn.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(240, 62, 62));
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        backroundPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    void setColor(JPanel panel) {
        panel.setBackground(new Color(255, 135, 135));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(250, 82, 82));
    }

    void changeColorMenu(JPanel panelSet, JPanel panelReset1, JPanel panelReset2) {
        setColor(panelSet);
        resetColor(panelReset1);
        resetColor(panelReset2);
    }

    void visiblePanel(JPanel visiblePanel, JPanel hiddenPanel1, JPanel hiddenPanel2) {
        visiblePanel.setVisible(true);
        hiddenPanel1.setVisible(false);
        hiddenPanel2.setVisible(false);
    }
    private void trainMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainMenuLabelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTrainMenuPanel, backgroundTestMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(trainPanel, testPanel, classificationPanel);
    }//GEN-LAST:event_trainMenuLabelMouseClicked

    private void testMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testMenuLabelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTestMenuPanel, backgroundTrainMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(testPanel, trainPanel, classificationPanel);
    }//GEN-LAST:event_testMenuLabelMouseClicked

    private void classificationMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classificationMenuLabelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundClassificationMenuPanel, backgroundTestMenuPanel, backgroundTrainMenuPanel);
        visiblePanel(classificationPanel, testPanel, trainPanel);
    }//GEN-LAST:event_classificationMenuLabelMouseClicked

    private void backgroundTrainMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundTrainMenuPanelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTrainMenuPanel, backgroundTestMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(trainPanel, testPanel, classificationPanel);
    }//GEN-LAST:event_backgroundTrainMenuPanelMouseClicked

    private void backgroundTestMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundTestMenuPanelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTestMenuPanel, backgroundTrainMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(testPanel, trainPanel, classificationPanel);
    }//GEN-LAST:event_backgroundTestMenuPanelMouseClicked

    private void backgroundClassificationMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundClassificationMenuPanelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundClassificationMenuPanel, backgroundTestMenuPanel, backgroundTrainMenuPanel);
        visiblePanel(classificationPanel, testPanel, trainPanel);
    }//GEN-LAST:event_backgroundClassificationMenuPanelMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void chooseTrainFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTrainFileBtnActionPerformed
        // TODO add your handling code here:
//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "JPG & GIF Images", "jpg", "gif");
//        chooser.setFileFilter(filter);
//        int returnVal = chooser.showOpenDialog(null);
//        if (returnVal == JFileChooser.APPROVE_OPTION) {
//            System.out.println("You chose to open this file: "
//                    + chooser.getSelectedFile().getName());
//        }
        FileDialog dialog = new FileDialog((Frame) null, "Select File to Open");
        dialog.setMode(FileDialog.LOAD);
        dialog.setVisible(true);
        String file = dialog.getFile();
        System.out.println(file + " chosen.");
    }//GEN-LAST:event_chooseTrainFileBtnActionPerformed

    private void trainModelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainModelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainModelBtnActionPerformed

    private void saveModelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveModelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveModelBtnActionPerformed

    private void chooseTestFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTestFileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseTestFileBtnActionPerformed

    private void testModelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testModelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testModelBtnActionPerformed

    private void chooseModelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseModelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseModelBtnActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField4ActionPerformed

    private void textField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField10ActionPerformed

    private void textField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField11ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField8ActionPerformed

    private void textField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField9ActionPerformed

    private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField3ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void textField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField6ActionPerformed

    private void textField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField7ActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportBtnActionPerformed

    private void predictFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictFileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_predictFileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("FlatLaf Light".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {

        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassificationHeadingLabel;
    private javax.swing.JPanel backgroundClassificationMenuPanel;
    private javax.swing.JPanel backgroundTestMenuPanel;
    private javax.swing.JPanel backgroundTrainMenuPanel;
    private javax.swing.JPanel backroundPanel;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton chooseModelBtn;
    private javax.swing.JButton chooseTestFileBtn;
    private javax.swing.JButton chooseTrainFileBtn;
    private javax.swing.JLabel classificationMenuLabel;
    private javax.swing.JPanel classificationPanel;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JTextArea infoTestModelTextArea;
    private javax.swing.JTextArea infoTrainModelTextArea;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel pathTestLabel;
    private javax.swing.JLabel pathTestLabel1;
    private javax.swing.JTextField pathTestTextField;
    private javax.swing.JTextField pathTestTextField1;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JButton predictBtn;
    private javax.swing.JButton predictFileBtn;
    private javax.swing.JTable predictTable;
    private javax.swing.JButton saveModelBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel testHeadingLabel;
    private javax.swing.JLabel testMenuLabel;
    private javax.swing.JButton testModelBtn;
    private javax.swing.JPanel testPanel;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField10;
    private javax.swing.JTextField textField11;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextField textField3;
    private javax.swing.JTextField textField4;
    private javax.swing.JTextField textField5;
    private javax.swing.JTextField textField6;
    private javax.swing.JTextField textField7;
    private javax.swing.JTextField textField8;
    private javax.swing.JTextField textField9;
    private javax.swing.JLabel trainHeadingLabel;
    private javax.swing.JLabel trainMenuLabel;
    private javax.swing.JButton trainModelBtn;
    private javax.swing.JPanel trainPanel;
    private javax.swing.JSeparator trainPathLine;
    private javax.swing.JLabel wineImg;
    // End of variables declaration//GEN-END:variables
}
