package App;

import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tranluan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        changeColorMenu(backgroundTrainMenuPanel, backgroundTestMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(trainPanel, testPanel, classificationPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup6 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        backroundPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        wineImg = new javax.swing.JLabel();
        backgroundClassificationMenuPanel = new javax.swing.JPanel();
        classificationMenuLabel = new javax.swing.JLabel();
        backgroundTestMenuPanel = new javax.swing.JPanel();
        testMenuLabel = new javax.swing.JLabel();
        backgroundTrainMenuPanel = new javax.swing.JPanel();
        trainMenuLabel = new javax.swing.JLabel();
        trainPanel = new javax.swing.JPanel();
        trainHeadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pathTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        testPanel = new javax.swing.JPanel();
        testHeadingLabel = new javax.swing.JLabel();
        pathTestLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pathTestTextField = new javax.swing.JTextField();
        classificationPanel = new javax.swing.JPanel();
        trainHeadingLabel2 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Red Wine Quality Measure");
        setBackground(new java.awt.Color(255, 249, 219));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        backroundPanel.setBackground(new java.awt.Color(255, 245, 245));
        backroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(250, 82, 82));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wineImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/wine-sm.png"))); // NOI18N
        wineImg.setText("jLabel5");
        sidePanel.add(wineImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 340));

        backgroundClassificationMenuPanel.setBackground(new java.awt.Color(250, 82, 82));
        backgroundClassificationMenuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundClassificationMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundClassificationMenuPanelMouseClicked(evt);
            }
        });

        classificationMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        classificationMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        classificationMenuLabel.setText("Wine Classification");
        classificationMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classificationMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classificationMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundClassificationMenuPanelLayout = new javax.swing.GroupLayout(backgroundClassificationMenuPanel);
        backgroundClassificationMenuPanel.setLayout(backgroundClassificationMenuPanelLayout);
        backgroundClassificationMenuPanelLayout.setHorizontalGroup(
            backgroundClassificationMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundClassificationMenuPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(classificationMenuLabel)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        backgroundClassificationMenuPanelLayout.setVerticalGroup(
            backgroundClassificationMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundClassificationMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classificationMenuLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(backgroundClassificationMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 250, 40));

        backgroundTestMenuPanel.setBackground(new java.awt.Color(250, 82, 82));
        backgroundTestMenuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundTestMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundTestMenuPanelMouseClicked(evt);
            }
        });

        testMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        testMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        testMenuLabel.setText("Test model");
        testMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundTestMenuPanelLayout = new javax.swing.GroupLayout(backgroundTestMenuPanel);
        backgroundTestMenuPanel.setLayout(backgroundTestMenuPanelLayout);
        backgroundTestMenuPanelLayout.setHorizontalGroup(
            backgroundTestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTestMenuPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(testMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        backgroundTestMenuPanelLayout.setVerticalGroup(
            backgroundTestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTestMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testMenuLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(backgroundTestMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        backgroundTrainMenuPanel.setBackground(new java.awt.Color(250, 82, 82));
        backgroundTrainMenuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundTrainMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundTrainMenuPanelMouseClicked(evt);
            }
        });

        trainMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trainMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        trainMenuLabel.setText("Train model");
        trainMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trainMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundTrainMenuPanelLayout = new javax.swing.GroupLayout(backgroundTrainMenuPanel);
        backgroundTrainMenuPanel.setLayout(backgroundTrainMenuPanelLayout);
        backgroundTrainMenuPanelLayout.setHorizontalGroup(
            backgroundTrainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTrainMenuPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(trainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        backgroundTrainMenuPanelLayout.setVerticalGroup(
            backgroundTrainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTrainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainMenuLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(backgroundTrainMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        backroundPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 242, 540));

        trainPanel.setBackground(new java.awt.Color(255, 245, 245));
        trainPanel.setForeground(new java.awt.Color(255, 82, 82));

        trainHeadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        trainHeadingLabel.setForeground(new java.awt.Color(250, 82, 82));
        trainHeadingLabel.setText("Train wine model");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 82, 82));
        jLabel1.setText("Path: ");

        jSeparator1.setBackground(new java.awt.Color(255, 82, 82));
        jSeparator1.setForeground(new java.awt.Color(255, 82, 82));

        pathTextField.setBackground(new java.awt.Color(255, 245, 245));
        pathTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jComboBox1.setForeground(new java.awt.Color(255, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decision tree", "KNN", "Naive Bayes", "Neural Network", "Support Vector Machine(SVM)" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 82, 82));
        jLabel2.setText("Algorithm ");

        javax.swing.GroupLayout trainPanelLayout = new javax.swing.GroupLayout(trainPanel);
        trainPanel.setLayout(trainPanelLayout);
        trainPanelLayout.setHorizontalGroup(
            trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trainPanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(trainHeadingLabel)
                .addGap(93, 93, 93))
            .addGroup(trainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 388, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(pathTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trainPanelLayout.setVerticalGroup(
            trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(trainHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(trainPanelLayout.createSequentialGroup()
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(trainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(357, Short.MAX_VALUE))
        );

        backroundPanel.add(trainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 530, 500));

        testPanel.setBackground(new java.awt.Color(255, 245, 245));
        testPanel.setForeground(new java.awt.Color(255, 82, 82));

        testHeadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        testHeadingLabel.setForeground(new java.awt.Color(250, 82, 82));
        testHeadingLabel.setText("Test wine model");

        pathTestLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pathTestLabel.setForeground(new java.awt.Color(255, 82, 82));
        pathTestLabel.setText("Path: ");

        jSeparator2.setBackground(new java.awt.Color(255, 82, 82));
        jSeparator2.setForeground(new java.awt.Color(255, 82, 82));

        pathTestTextField.setBackground(new java.awt.Color(255, 245, 245));
        pathTestTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testPanelLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(testHeadingLabel)
                .addGap(93, 93, 93))
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pathTestLabel)
                .addGap(40, 40, 40)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(pathTestTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(testHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathTestLabel)
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addComponent(pathTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(394, Short.MAX_VALUE))
        );

        backroundPanel.add(testPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 530, 500));

        classificationPanel.setBackground(new java.awt.Color(255, 245, 245));
        classificationPanel.setForeground(new java.awt.Color(255, 82, 82));

        trainHeadingLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        trainHeadingLabel2.setForeground(new java.awt.Color(250, 82, 82));
        trainHeadingLabel2.setText("Wine Classification");

        javax.swing.GroupLayout classificationPanelLayout = new javax.swing.GroupLayout(classificationPanel);
        classificationPanel.setLayout(classificationPanelLayout);
        classificationPanelLayout.setHorizontalGroup(
            classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classificationPanelLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(trainHeadingLabel2)
                .addGap(93, 93, 93))
        );
        classificationPanelLayout.setVerticalGroup(
            classificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classificationPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(trainHeadingLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );

        backroundPanel.add(classificationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 530, 500));

        closeBtn.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(240, 62, 62));
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        backroundPanel.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    void setColor(JPanel panel) {
        panel.setBackground(new Color(255, 135, 135));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(250, 82, 82));
    }

    void changeColorMenu(JPanel panelSet, JPanel panelReset1, JPanel panelReset2) {
        setColor(panelSet);
        resetColor(panelReset1);
        resetColor(panelReset2);
    }

    void visiblePanel(JPanel visiblePanel, JPanel hiddenPanel1, JPanel hiddenPanel2) {
        visiblePanel.setVisible(true);
        hiddenPanel1.setVisible(false);
        hiddenPanel2.setVisible(false);
    }
    private void trainMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainMenuLabelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTrainMenuPanel, backgroundTestMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(trainPanel, testPanel, classificationPanel);
    }//GEN-LAST:event_trainMenuLabelMouseClicked

    private void testMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testMenuLabelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTestMenuPanel, backgroundTrainMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(testPanel, trainPanel, classificationPanel);
    }//GEN-LAST:event_testMenuLabelMouseClicked

    private void classificationMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classificationMenuLabelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundClassificationMenuPanel, backgroundTestMenuPanel, backgroundTrainMenuPanel);
        visiblePanel(classificationPanel, testPanel, trainPanel);
    }//GEN-LAST:event_classificationMenuLabelMouseClicked

    private void backgroundTrainMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundTrainMenuPanelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTrainMenuPanel, backgroundTestMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(trainPanel, testPanel, classificationPanel);
    }//GEN-LAST:event_backgroundTrainMenuPanelMouseClicked

    private void backgroundTestMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundTestMenuPanelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundTestMenuPanel, backgroundTrainMenuPanel, backgroundClassificationMenuPanel);
        visiblePanel(testPanel, trainPanel, classificationPanel);
    }//GEN-LAST:event_backgroundTestMenuPanelMouseClicked

    private void backgroundClassificationMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundClassificationMenuPanelMouseClicked
        // TODO add your handling code here:
        changeColorMenu(backgroundClassificationMenuPanel, backgroundTestMenuPanel, backgroundTrainMenuPanel);
        visiblePanel(classificationPanel, testPanel, trainPanel);
    }//GEN-LAST:event_backgroundClassificationMenuPanelMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundClassificationMenuPanel;
    private javax.swing.JPanel backgroundTestMenuPanel;
    private javax.swing.JPanel backgroundTrainMenuPanel;
    private javax.swing.JPanel backroundPanel;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel classificationMenuLabel;
    private javax.swing.JPanel classificationPanel;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pathTestLabel;
    private javax.swing.JTextField pathTestTextField;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel testHeadingLabel;
    private javax.swing.JLabel testMenuLabel;
    private javax.swing.JPanel testPanel;
    private javax.swing.JLabel trainHeadingLabel;
    private javax.swing.JLabel trainHeadingLabel2;
    private javax.swing.JLabel trainMenuLabel;
    private javax.swing.JPanel trainPanel;
    private javax.swing.JLabel wineImg;
    // End of variables declaration//GEN-END:variables
}
